name: selective_gesture_wrapper
description: "A lightweight widget that selectively absorbs or passes gestures to its child."
version: 0.0.1
homepage: https://github.com/sourabhappdev/selective_gesture_wrapper/tree/main
repository: https://github.com/sourabhappdev/selective_gesture_wrapper/tree/main
issue_tracker: https://github.com/sourabhappdev/selective_gesture_wrapper/issues

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
